openapi: 3.1.0
info:
  version: 1.0.0
  title: cloud-vertx
  license:
    identifier: MIT
    name: MIT License
servers:
  - url: 'http:127.0.0.1:8201'
security:
  - bearerAuth: [ ]         # use the same name as above
paths:
  /code:
    get:
      security: [ ]
      summary: 获取验证码
      operationId: VerifyCodeHandler
      tags:
        - 登录
      parameters:
        - name: randomStr
          in: query
          description: 申请验证码的随机字符串
          required: true
          schema:
            type: string
          allowEmptyValue: false
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginByUsernameHandlerAo'
  /login/token/byUsername:
    post:
      security: [ ]
      summary: 用户登录
      operationId: LoginByUsernameHandler
      tags:
        - 登录
      parameters:
        - name: code
          in: query
          description: 用户输入的验证码
          required: true
          schema:
            type: string
        - name: randomStr
          in: query
          description: 申请验证码的随机字符串
          required: true
          schema:
            type: string
      requestBody:
        description: 用户登录
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginByUsernameHandlerAo'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginByUsernameHandlerVo'
  /user/permissions:
    get:
      summary: 获取用户权限
      operationId: UserPermissionsHandler
      tags:
        - 用户
      responses:
        '200':
          description: 权限合集
  /user/routers:
    get:
      summary: 获取用户路由
      operationId: UserRoutersHandler
      tags:
        - 用户
      responses:
        '200':
          description: 路由合集
  /user:
    get:
      summary: 查询用户（分页）
      operationId: UserPageHandler
      tags:
        - 用户
      parameters:
        - name: pageSize
          in: query
          description: 页数
          required: true
          schema:
            type: integer
            nullable: false
        - name: pageNum
          in: query
          description: 页码
          required: true
          schema:
            type: integer
            nullable: false
        - name: username
          in: query
          description: 用户名
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 用户集合
  /dept/tree:
    get:
      summary: 获取部门树
      operationId: DeptTreeHandler
      tags:
        - 部门
      parameters:
        - name: deptName
          in: query
          description: 部门名称
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 部门树
  /test:
    get:
      security: [ ]
      summary: test
      operationId: test
      tags:
        - test
      parameters:
        - name: username
          in: query
          description: 用户名
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A paged array of pets
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    LoginByUsernameHandlerAo:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: >-
            密码（需加密）加密方式 aes 编码Base64 模式 CFB 填充 NoPadding 密钥 密钥字符串 偏移量 密钥字符串
            在线生成网址： <a href="https://www.mklab.cn/utils/aes">点击跳转</a>
    LoginByUsernameHandlerVo:
      type: object
      properties: { }
